"""
Configuration module for TW Code QA system
配置模組 - 包含所有系統配置
"""

# Settings configuration
from .settings import (
    Environment,
    LogLevel,
    MemoryManagementConfig,
    ProcessingConfig,
    IOOptimizationConfig,
    CachingConfig,
    PerformanceConfig,
    ApiKeysConfig,
    DataProtectionConfig,
    NetworkConfig,
    SecurityConfig,
    HealthCheckConfig,
    MetricsConfig,
    AlertsConfig,
    MonitoringConfig,
    ValidationConfig,
    TransformationConfig,
    OutputConfig,
    DataProcessingConfig,
    EnvironmentConfig,
    SystemSettings,
    DEFAULT_SETTINGS,
    ENVIRONMENT_CONFIGS,
    SYSTEM_PATHS,
    FEATURE_FLAGS,
    PERFORMANCE_CONFIGS,
    SECURITY_CONFIGS,
    MONITORING_CONFIGS,
    DATA_PROCESSING_CONFIGS,
    CURRENT_ENVIRONMENT,
    get_environment,
    set_environment,
    get_config_for_environment,
    is_development,
    is_production,
)

# LLM configuration
from .llm_config import (
    LLMProvider,
    ModelTier,
    RetryConfig,
    RateLimitConfig,
    ModelConfig,
    AgentModelConfig,
    DEFAULT_LLM_CONFIGS,
    AGENT_MODEL_CONFIGS,
    COST_TRACKING_CONFIG,
    MODEL_PRICING,
    QUALITY_THRESHOLDS,
    get_model_config,
    get_agent_config,
    calculate_cost,
)

# Logging configuration
from .logging_config import (
    LogLevel as LoggingLogLevel,  # 避免與 settings 的 LogLevel 衝突
    LogFormat,
    HandlerConfig,
    FormatterConfig,
    LoggerConfig,
    LoggingSystemConfig,
    DEFAULT_LOG_DIR,
    AGENT_LOG_CONFIGS,
    LOG_FILTERS,
    ensure_log_directory,
    get_handler_configs,
    get_logging_config,
    get_development_logging_config,
    get_production_logging_config,
    get_testing_logging_config,
    LoggerNames,
)

__all__ = [
    # Settings - Enums
    "Environment",
    "LogLevel",
    
    # Settings - TypedDict classes
    "MemoryManagementConfig",
    "ProcessingConfig",
    "IOOptimizationConfig", 
    "CachingConfig",
    "PerformanceConfig",
    "ApiKeysConfig",
    "DataProtectionConfig",
    "NetworkConfig",
    "SecurityConfig",
    "HealthCheckConfig",
    "MetricsConfig",
    "AlertsConfig",
    "MonitoringConfig",
    "ValidationConfig",
    "TransformationConfig",
    "OutputConfig",
    "DataProcessingConfig",
    "EnvironmentConfig",
    "SystemSettings",
    
    # Settings - Configuration dictionaries
    "DEFAULT_SETTINGS",
    "ENVIRONMENT_CONFIGS",
    "SYSTEM_PATHS",
    "FEATURE_FLAGS",
    "PERFORMANCE_CONFIGS",
    "SECURITY_CONFIGS",
    "MONITORING_CONFIGS",
    "DATA_PROCESSING_CONFIGS",
    "CURRENT_ENVIRONMENT",
    
    # Settings - Functions
    "get_environment",
    "set_environment",
    "get_config_for_environment",
    "is_development",
    "is_production",
    
    # LLM Configuration
    "LLMProvider",
    "ModelTier",
    "RetryConfig",
    "RateLimitConfig",
    "ModelConfig",
    "AgentModelConfig",
    "DEFAULT_LLM_CONFIGS",
    "AGENT_MODEL_CONFIGS",
    "COST_TRACKING_CONFIG",
    "MODEL_PRICING",
    "QUALITY_THRESHOLDS",
    "get_model_config",
    "get_agent_config",
    "calculate_cost",
    
    # Logging Configuration  
    "LoggingLogLevel",
    "LogFormat",
    "HandlerConfig",
    "FormatterConfig",
    "LoggerConfig",
    "LoggingSystemConfig",
    "DEFAULT_LOG_DIR",
    "AGENT_LOG_CONFIGS",
    "LOG_FILTERS",
    "ensure_log_directory",
    "get_handler_configs",
    "get_logging_config",
    "get_development_logging_config",
    "get_production_logging_config",
    "get_testing_logging_config",
    "LoggerNames",
]